config/routes.rb
Rails.application.routes.draw do

  root "projects#index" 

  resources :projects do
    resources :tickets 
  end

  resources :users

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true

	has_many :tickets, dependent: :delete_all
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  	belongs_to :project
  	belongs_to :user

  	validates :title, presence: true
	validates :description, 
					presence: true,
                    length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	private

		def require_signin!
		    if current_user.nil?
		      flash[:error] =
		      "You need to sign in or sign up before continuing."
		      redirect_to signin_url
			end
		end
		helper_method :require_signin!

		def current_user
		  @current_user ||= User.find(session[:user_id]) if session[:user_id]
		end
		helper_method :current_user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authorize_admin!, except: [:index, :show]
	before_action :set_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
	  @project = Project.new(project_params)

	  if @project.save
	    flash[:notice] = "Project has been created."
	    
	    redirect_to @project
	  else
		flash[:alert] = "Project has not been created."

    	render "new"
	  end 
	end

	def show

	end

	def edit

	end

	def update
		if @project.update(project_params)
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else 
			flash[:alert] = "Project has not been updated."
	    	render "edit"
	    end
	end

	def destroy
	  	@project.destroy

	  	flash[:notice] = "Project has been destroyed."
	  	
	  	redirect_to projects_path
	end	

	private

	  def project_params
	    params.require(:project).permit(:name, :description)
	  end

	  def set_project
	    @project = Project.find(params[:id])
	  rescue ActiveRecord::RecordNotFound
	    flash[:alert] = "The project you were looking" +
	                    " for could not be found."
	    redirect_to projects_path
	  end

	  def authorize_admin!
    	require_signin!

    	unless current_user.admin?
      		flash[:alert] = "You must be an admin to do that."
      		redirect_to root_path
		end 
	  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		# @session = Session.new
	end

	def create
	  user = User.where(:name => params[:signin][:name]).first

	  if user && user.authenticate(params[:signin][:password])
	    session[:user_id] = user.id
	    flash[:notice] = "Signed in successfully."
	    
	    redirect_to root_url
	  else
	    flash[:error] = "Sorry."
	    render :new
	  end
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	before_action :require_signin!, except: [:show, :index]

	def new
		@ticket = @project.tickets.build
	end

	def create
	  @ticket = @project.tickets.build(ticket_params)
	  @ticket.user = current_user
	  
	  if @ticket.save
	    flash[:notice] = "Ticket has been created."
	    redirect_to [@project, @ticket]
	  else
	    flash[:alert] = "Ticket has not been created."
	    render "new"
	  end
	end

	def edit 
	end

	def update
	  if @ticket.update(ticket_params)
	    flash[:notice] = "Ticket has been updated."
	    redirect_to [@project, @ticket]
	  else
	    flash[:alert] = "Ticket has not been updated."
	    render action: "edit"
	  end
	end

	def destroy
	  @ticket.destroy
	  flash[:notice] = "Ticket has been deleted."
	  
	  redirect_to @project
	end

	private

		def ticket_params
    		params.require(:ticket).permit(:title, :description)
		end

		def set_project
	    	@project = Project.find(params[:project_id])
	  	end

	  	def set_ticket
  			@ticket = @project.tickets.find(params[:id])
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_profile, only: [:show, :edit, :update]

	def new
	  @user = User.new
	end

	def create
	  	@user = User.new(user_params)

	  	if @user.save
	    	flash[:notice] = "You have signed up successfully."
	    	redirect_to projects_path
	  	else
	    	render :new
		end 
	end

  	def show
  	end

	def edit 
	end

	def update
	  if @user.update(user_params)
	    flash[:notice] = "Profile has been updated."
	    redirect_to [@user]
	  else
	    flash[:alert] = "Profile has not been updated."
	    render action: "edit"
	  end
	end

private

  	def user_params
		params.require(:user).permit(:name,
									:email,
									:password,
									:password_confirmation)

	end

	def set_profile 
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
	    unless parts.empty?
	      content_for :title do
	        (parts << "Ticketee").join(" - ")
	      end
		end 
	end

	def admins_only(&block)
	  	block.call if current_user.try(:admin?)
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
	<% if content_for?(:title) %>
		<%= yield(:title) %>
	<% else %>
	    Ticketee
	<% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% user = current_user %>

  <nav>
    <ul>
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Sign up", new_user_path %></li>
      <li><%= link_to "Sign in", signin_path %></li>
      <li><%= link_to "View profile", user %></li>
    </ul>
  </nav>

  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
    
  <%= f.submit %>


	<% if @project.errors.any? %>

	 <div id="error_explanation">

	   <h2><%= pluralize(@project.errors.count, "error") %>
	     prohibited this project from being saved:</h2>

	   <ul>
	   <% @project.errors.full_messages.each do |msg| %>
	     <li><%= msg %></li>
	   <% end %>
	   </ul>
	   
	 </div>

	<% end %>

<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render "form" %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<h2><%= @project.name %></h2>
<p><%= @project.description %></p>

<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project",
       project_path(@project),
       method: :delete,
       data: { confirm:
                 "Are you sure you want to delete this project?"
             } %>	
<% end %>

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>

  <% if @ticket.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@ticket.errors.count, "error") %>
     prohibited this ticket from being saved:</h2>
     
     <ul>
     <% @ticket.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p> 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>

<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>

<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>

<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>

  	<h2><%= @ticket.title %></h2>
  	<span id='author'>Created by <%= @ticket.user.email %></span>

  	<%= simple_format(@ticket.description) %>

  	<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>

  	<%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
  data: { confirm: "Are you sure you want to delete this ticket?"} %>

  	<%= link_to "Go back to project", @ticket.project %>


</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@user.errors.count, "error") %>
       prohibited this user from being saved:</h2>
     <ul>
     <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>

  <p>
    <%= f.label :name, "Username" %><br>
    <%= f.text_field :name %>
  </p> 

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p> 

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <% if @user.new_record? %>
    <%= f.submit "Sign up" %>
  <% else %>
    <%= f.submit "Update Profile" %>
  <% end %>
  
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<% title(@user.name, "User Profile") %>

<h2><%= @user.name %></h2>
<h2><%= @user.email %></h2>

<%= link_to "Edit Profile", edit_user_path(@user) %>